In [ ]:
!pip install numpy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [2]:
import numpy as np

In [ ]:
my_list = [1,2,3]
n = np.array(my_list)
n

array([1, 2, 3])

In [ ]:
type(n)

numpy.ndarray

In [ ]:
n = np.array({2,3,4})
print(n)

{2, 3, 4}


In [ ]:
n = np.array([[1,2,3],[2,4,5],[3,4,5]])
n

<ipython-input-14-eac1fc3e18b6>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  n = np.array([[1,2],[2,4,5],[3,4,5]])


array([list([1, 2]), list([2, 4, 5]), list([3, 4, 5])], dtype=object)

In [ ]:
print(n)

[[1 2 3]
 [2 4 5]
 [3 4 5]]


In [ ]:
print(n.shape)

(3, 3)


In [ ]:
n = np.arange(0,100,3)
print(n)

[ 0  3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69
 72 75 78 81 84 87 90 93 96 99]


In [ ]:
n = np.zeros((3,3))
n

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
n = np.zeros(5)
n

array([0., 0., 0., 0., 0.])

In [ ]:
n = np.ones((3,2))
n
len(n)

3

In [ ]:
n=np.ones(5)
n

array([1., 1., 1., 1., 1.])

In [ ]:
n= np.eye(3)
n

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
n = np.eye(10)
n

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [ ]:
len(n)

10

In [ ]:
n.reshape(50,2)

In [ ]:
m = np.linspace(0,7,10)
m

array([0.        , 0.77777778, 1.55555556, 2.33333333, 3.11111111,
       3.88888889, 4.66666667, 5.44444444, 6.22222222, 7.        ])

In [ ]:
m.reshape(5,2)

array([[0.        , 0.77777778],
       [1.55555556, 2.33333333],
       [3.11111111, 3.88888889],
       [4.66666667, 5.44444444],
       [6.22222222, 7.        ]])

In [ ]:
m

array([0.        , 0.77777778, 1.55555556, 2.33333333, 3.11111111,
       3.88888889, 4.66666667, 5.44444444, 6.22222222, 7.        ])

In [ ]:
m.resize(2,5)

In [ ]:
m

array([[0.        , 0.77777778, 1.55555556, 2.33333333, 3.11111111],
       [3.88888889, 4.66666667, 5.44444444, 6.22222222, 7.        ]])

In [ ]:
p = np.random.rand(3,2)
p

array([[0.16625012, 0.12532153],
       [0.42415375, 0.16094262],
       [0.13288392, 0.43266356]])

In [ ]:
np.random.randn(3,6)

array([[-0.16475122,  0.41069926,  0.67510396, -0.74546756,  0.50711309,
        -1.68030649],
       [-0.27739571,  0.02824355,  1.32403018,  0.34417532, -1.73107734,
         0.35693382],
       [ 0.24407462,  0.08202342,  0.92507291,  0.01223141,  0.05695653,
        -0.32604184]])

In [ ]:
mn=np.random.randint(3,100,15)
mn

array([71, 21, 21, 64, 53, 80, 78, 42, 38, 64, 70, 85, 93, 52, 61])

In [ ]:
mn.reshape(3,5)

array([[71, 21, 21, 64, 53],
       [80, 78, 42, 38, 64],
       [70, 85, 93, 52, 61]])

In [ ]:
len(mn)

15

In [ ]:
mn.resize(5,3)
mn

array([[71, 21, 21],
       [64, 53, 80],
       [78, 42, 38],
       [64, 70, 85],
       [93, 52, 61]])

In [ ]:
len(mn)

5

In [ ]:
np.random.randint(3,30,(5,3))

array([[20, 12, 28],
       [19,  6, 23],
       [ 6, 12, 23],
       [15, 24,  6],
       [21, 12, 10]])

In [ ]:
na = np.arange(64)
na

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63])

In [ ]:
na[4]

4

In [ ]:
na[-1]

63

In [ ]:
na[2:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52,
       53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63])

In [ ]:
na[5:-7]

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38,
       39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55,
       56])

In [ ]:
na.resize(8,8)
na

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60, 61, 62, 63]])

In [ ]:
na[4]

array([32, 33, 34, 35, 36, 37, 38, 39])

In [ ]:
na[4,6]

38

In [ ]:
na[-1,-1]

63

In [ ]:
na[2,2:]

array([18, 19, 20, 21, 22, 23])

In [ ]:
na[3:,3:]

array([[27, 28, 29, 30, 31],
       [35, 36, 37, 38, 39],
       [43, 44, 45, 46, 47],
       [51, 52, 53, 54, 55],
       [59, 60, 61, 62, 63]])

In [ ]:
na[3:]

array([[24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60, 61, 62, 63]])

In [ ]:
na>25

array([[False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False],
       [False, False,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True]])

In [ ]:
na[na>25]

array([26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42,
       43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59,
       60, 61, 62, 63])

In [ ]:
na[na>25]=25
na

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 25, 25, 25, 25, 25, 25],
       [25, 25, 25, 25, 25, 25, 25, 25],
       [25, 25, 25, 25, 25, 25, 25, 25],
       [25, 25, 25, 25, 25, 25, 25, 25],
       [25, 25, 25, 25, 25, 25, 25, 25]])

In [ ]:
na1 = na[0:,0:]
na1

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 25, 25, 25, 25, 25, 25],
       [25, 25, 25, 25, 25, 25, 25, 25],
       [25, 25, 25, 25, 25, 25, 25, 25],
       [25, 25, 25, 25, 25, 25, 25, 25],
       [25, 25, 25, 25, 25, 25, 25, 25]])

In [ ]:
na2=na.copy()
na2

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 25, 25, 25, 25, 25, 25],
       [25, 25, 25, 25, 25, 25, 25, 25],
       [25, 25, 25, 25, 25, 25, 25, 25],
       [25, 25, 25, 25, 25, 25, 25, 25],
       [25, 25, 25, 25, 25, 25, 25, 25]])

In [ ]:
na2[na2>5]=5
na2

array([[0, 1, 2, 3, 4, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5, 5]])

In [ ]:
na

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 25, 25, 25, 25, 25, 25],
       [25, 25, 25, 25, 25, 25, 25, 25],
       [25, 25, 25, 25, 25, 25, 25, 25],
       [25, 25, 25, 25, 25, 25, 25, 25],
       [25, 25, 25, 25, 25, 25, 25, 25]])

In [ ]:
np.random.rand(3,3)

array([[0.77815675, 0.87001215, 0.97861834],
       [0.79915856, 0.46147936, 0.78052918],
       [0.11827443, 0.63992102, 0.14335329]])

In [ ]:
np.random.seed(9)
np.random.random((3,3))

array([[0.01037415, 0.50187459, 0.49577329],
       [0.13382953, 0.14211109, 0.21855868],
       [0.41850818, 0.24810117, 0.08405965]])

In [4]:
a1=np.arange(2,10)
a1

array([2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
a1.resize(2,4)
a1

array([[2, 3, 4, 5],
       [6, 7, 8, 9]])

In [7]:
a2=np.arange(1,9)
a2.resize(2,4)
a2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [8]:
a1+a2

array([[ 3,  5,  7,  9],
       [11, 13, 15, 17]])

In [10]:
np.add(a1,a2)

array([[ 3,  5,  7,  9],
       [11, 13, 15, 17]])

In [11]:
a1-a2

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [13]:
np.subtract(a1,a2)

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [14]:
a1*a2

array([[ 2,  6, 12, 20],
       [30, 42, 56, 72]])

In [15]:
a3=np.array([2,1,3,4])
a3

array([2, 1, 3, 4])

In [16]:
np.multiply(a1,a3)

array([[ 4,  3, 12, 20],
       [12,  7, 24, 36]])

In [17]:
np.matmul(a1,a3)

array([39, 79])

In [22]:
a1=np.array([[1,2,3,4],[2,4,6,5],[2,4,3,2]])
a1

array([[1, 2, 3, 4],
       [2, 4, 6, 5],
       [2, 4, 3, 2]])

In [28]:
a2=np.array([[2,3,4,5],[4,3,2,1]])
a1+a2

ValueError: ignored

In [34]:
a2=np.array([2,3,4,5])
a1*a2

array([[ 2,  6, 12, 20],
       [ 4, 12, 24, 25],
       [ 4, 12, 12, 10]])

In [33]:
a4=np.array([1,2,3,4])
a5=np.array([[1],[2],[3],[4]])
a4*a5

array([[ 1,  2,  3,  4],
       [ 2,  4,  6,  8],
       [ 3,  6,  9, 12],
       [ 4,  8, 12, 16]])

In [35]:
a4/a5

array([[1.        , 2.        , 3.        , 4.        ],
       [0.5       , 1.        , 1.5       , 2.        ],
       [0.33333333, 0.66666667, 1.        , 1.33333333],
       [0.25      , 0.5       , 0.75      , 1.        ]])

In [36]:
a4//a5

array([[1, 2, 3, 4],
       [0, 1, 1, 2],
       [0, 0, 1, 1],
       [0, 0, 0, 1]])

In [37]:
a4%a5

array([[0, 0, 0, 0],
       [1, 0, 1, 0],
       [1, 2, 0, 1],
       [1, 2, 3, 0]])

In [38]:
a4**2

array([ 1,  4,  9, 16])

In [39]:
np.square(a4)

array([ 1,  4,  9, 16])

In [40]:
np.exp(a4)

array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [41]:
np.log(a4)

array([0.        , 0.69314718, 1.09861229, 1.38629436])

In [45]:
%timeit np.sum(np.arange(100))
%timeit sum(range(100))

5.82 µs ± 606 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
2.34 µs ± 76.4 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [46]:
np.mean(a4)

2.5

In [47]:
np.min(a4)

1

In [48]:
np.max(a4)

4

In [49]:
np.std(a4)

1.118033988749895

In [50]:
np.var(a4)

1.25

In [52]:
np.sqrt(np.var(a4))

1.118033988749895

In [57]:
np.random.seed(0)
a1=np.random.randint(0,10,(3,5))
a1

array([[5, 0, 3, 3, 7],
       [9, 3, 5, 2, 4],
       [7, 6, 8, 8, 1]])

In [58]:
np.random.seed(0)
a2=np.random.randint(0,10,(3,5))
a2

array([[5, 0, 3, 3, 7],
       [9, 3, 5, 2, 4],
       [7, 6, 8, 8, 1]])

In [59]:
np.multiply(a1,a2)

array([[25,  0,  9,  9, 49],
       [81,  9, 25,  4, 16],
       [49, 36, 64, 64,  1]])

In [60]:
np.dot(a1,a2)

ValueError: ignored

In [61]:
np.dot(a1.T,a2)

array([[155,  69, 116,  89,  78],
       [ 69,  45,  63,  54,  18],
       [116,  63,  98,  83,  49],
       [ 89,  54,  83,  77,  37],
       [ 78,  18,  49,  37,  66]])

In [4]:
sales = np.random.randint(1,20,(5,3))
sales

array([[16, 12,  2],
       [ 2, 17,  5],
       [ 1,  9,  7],
       [16, 15, 17],
       [ 3, 10,  5]])

In [5]:
amount = np.array([10,8,2])
amount

array([10,  8,  2])

In [6]:
np.dot(sales,amount)

array([260, 166,  96, 314, 120])

In [7]:
sales.shape, amount.shape

((5, 3), (3,))

In [8]:
sales>amount

array([[ True,  True, False],
       [False,  True,  True],
       [False,  True,  True],
       [ True,  True,  True],
       [False,  True,  True]])

In [9]:
new_arra = sales>=amount
new_arra

array([[ True,  True,  True],
       [False,  True,  True],
       [False,  True,  True],
       [ True,  True,  True],
       [False,  True,  True]])

In [10]:
type(new_arra),new_arra.dtype

(numpy.ndarray, dtype('bool'))

In [13]:
array1 = np.random.randint(20,size=(5,3))
array1

array([[ 4,  1, 11],
       [ 7, 18, 12],
       [ 5,  6, 11],
       [ 0,  6,  9],
       [18,  0,  4]])

In [14]:
np.sort(array1)

array([[ 1,  4, 11],
       [ 7, 12, 18],
       [ 5,  6, 11],
       [ 0,  6,  9],
       [ 0,  4, 18]])

In [16]:
np.sort(array1,axis=0)

array([[ 0,  0,  4],
       [ 4,  1,  9],
       [ 5,  6, 11],
       [ 7,  6, 11],
       [18, 18, 12]])

In [18]:
array1

array([[ 4,  1, 11],
       [ 7, 18, 12],
       [ 5,  6, 11],
       [ 0,  6,  9],
       [18,  0,  4]])

In [19]:
np.argsort(array1)

array([[1, 0, 2],
       [0, 2, 1],
       [0, 1, 2],
       [0, 1, 2],
       [1, 2, 0]])

In [20]:
np.argsort(array1, axis=0)

array([[3, 4, 4],
       [0, 0, 3],
       [2, 2, 0],
       [1, 3, 2],
       [4, 1, 1]])

In [21]:
np.argmax(array1)

4

In [22]:
np.argmin(array1)

9

In [23]:
np.argmax(array1,axis=0)

array([4, 1, 1])

In [24]:
np.argmax(array1,axis=1)

array([2, 1, 2, 2, 0])

In [25]:
np.argmin(array1,axis=0)

array([3, 4, 4])

In [26]:
np.argmin(array1,axis=1)

array([1, 0, 0, 0, 1])

In [45]:
import matplotlib.pyplot as plt
from matplotlib.image import imread

dog = imread('C:/Users/susmi/Downloads/image.png')
dog.shape
#here showing erro because it is unable to get the location as it is online tool, tried the same in jupyter notebook ran successfully

FileNotFoundError: ignored